// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmsbw0ohfdWU01FhKqi4e6oWieepQlZnA',
    appId: '1:729677328267:web:7ca0f0c6f44648d79ec98e',
    messagingSenderId: '729677328267',
    projectId: 'test-project-f32e0',
    authDomain: 'test-project-f32e0.firebaseapp.com',
    storageBucket: 'test-project-f32e0.firebasestorage.app',
    measurementId: 'G-MHK72DEVL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsoDkxyGYq6ihofdOhZQQNfbxYP5qRtM',
    appId: '1:729677328267:android:72fe24a50f8686099ec98e',
    messagingSenderId: '729677328267',
    projectId: 'test-project-f32e0',
    storageBucket: 'test-project-f32e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqBvmS4BiGb4HsDoMGKifHPOz-PwWmQEs',
    appId: '1:729677328267:ios:e924241ee0fdc0f39ec98e',
    messagingSenderId: '729677328267',
    projectId: 'test-project-f32e0',
    storageBucket: 'test-project-f32e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqBvmS4BiGb4HsDoMGKifHPOz-PwWmQEs',
    appId: '1:729677328267:ios:e924241ee0fdc0f39ec98e',
    messagingSenderId: '729677328267',
    projectId: 'test-project-f32e0',
    storageBucket: 'test-project-f32e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmsbw0ohfdWU01FhKqi4e6oWieepQlZnA',
    appId: '1:729677328267:web:79cf03322d016bba9ec98e',
    messagingSenderId: '729677328267',
    projectId: 'test-project-f32e0',
    authDomain: 'test-project-f32e0.firebaseapp.com',
    storageBucket: 'test-project-f32e0.firebasestorage.app',
    measurementId: 'G-H85L1D4H40',
  );
}
